### ISSUE TITLE
How can I type in a logarithmic spiral equation with **e** 

### ISSUE THREAD

**Issue by stillpointx** [WannesMalfait/Blender-Add-ons#7]
Typing in logarithmic spiral equation with **e** 

![screenshot-February-26-2022-03-07-10](https://user-images.githubusercontent.com/28985314/155835576-f7e124c7-6d99-4622-b2d5-511ee3d64626.png)

How would I go about typing this in?

Also when I try I get an error.  I'm using Blender 3.1.0 beta alone with Node Math Formula 1.2.1

```
Python: Traceback (most recent call last):
  File "/home/rt/.config/blender/3.1/scripts/addons/math_formula/main.py", line 844, in modal
    return bpy.ops.node.mf_attribute_math_formula_add(
  File "/home/rt/Downloads/000del temp handbrake/blender-3.1.0-beta+v31.517afcc858b0-linux.x86_64-release/blender-3.1.0-beta+v31.517afcc858b0-linux.x86_64-release/3.1/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/rt/.config/blender/3.1/scripts/addons/math_formula/main.py", line 598, in execute
    node = self.add_math_node(
  File "/home/rt/.config/blender/3.1/scripts/addons/math_formula/main.py", line 489, in add_math_node
    node = tree.nodes.new(type="GeometryNodeAttributeMath")
RuntimeError: Error: Node type GeometryNodeAttributeMath undefined

location: /home/rt/Downloads/000del temp handbrake/blender-3.1.0-beta+v31.517afcc858b0-linux.x86_64-release/blender-3.1.0-beta+v31.517afcc858b0-linux.x86_64-release/3.1/scripts/modules/bpy/ops.py:132



location: <unknown location>:-1

```

![math error](https://user-images.githubusercontent.com/28985314/155835947-63e1f266-d2d3-4ded-a64e-d746ad63ff5b.gif)

![image](https://user-images.githubusercontent.com/28985314/155835967-f8413ced-2aa0-4df1-b5db-e07492adf524.png)

**Comment by WannesMalfait** [comment]
The error happens because the addon tries to add attribute math nodes, which aren't supported anymore in blender 3.0+. You can still create a formula using the <kbd>Alt</kbd> + <kbd> F </kbd> menu. I'm working on a version which works in 3.0+ and uses the new fields system in geometry nodes (could still take a while). Once that's done I'll close this issue.

To create a formula containing `e` you have two options:
- You can use the `exp` function from the math node (`exp(x) = e^x`)
- You can get the value for `e` by accessing it through python: `!(e)` just like `!(pi)`, and then do what you want with it.

**Comment by stillpointx** [comment]
Thanks for the Update and great add-on.

**Comment by WannesMalfait** [comment]
The latest versions now work with fields, so I'll close this

**Comment by stillpointx** [comment]
Thanks!
