### ISSUE TITLE
Crash in math_formula addon

### ISSUE THREAD

**Issue by redweasel** [WannesMalfait/Blender-Add-ons#8]
If I press Alt+F and type "cos(x)sin(x)" I get this error, which causes the UI to stay open.
```
Error: Python: Traceback (most recent call last):
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/main.py", line 825, in modal
    res = compiler.compile(self.formula)
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/parser.py", line 415, in compile
    parser.declaration()
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/parser.py", line 194, in declaration
    self.statement()
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/parser.py", line 142, in statement
    self.expression()
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/parser.py", line 139, in expression
    self.parse_precedence(Precedence.ASSIGNMENT)
  File "/home/hd/.config/blender/3.5/scripts/addons/math_formula/parser.py", line 125, in parse_precedence
    infix_rule(self, can_assign)
TypeError: 'NoneType' object is not callable
```

**Comment by redweasel** [comment]
Ok, my mistake, I was on master. The mf_b3_fields branch doesn't have this problem. It instead creates a Math Cosine and a Math Sine node.
